server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

person:
  name: zhangsan
  age: 13
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - wangwu
  dog:
    name: nihao
    age: 2
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
